import { WorkspaceAnalysisService, WorkspaceAnalysis } from "./workspace-analysis.service";
import {
  RepositoryKnowledgeService,
  RepositoryKnowledgeResult,
  KnowledgeRetrievalOptions,
  KnowledgeRetrievalStats,
} from "./repository-knowledge.service";
import { LLMService } from "./llm.service";
import { SourceReference, ContextDomain } from "./chat-context.service";
import { executeWithTelemetry } from "./ai-service.wrapper";
import { AIServiceBase } from "./ai-service.base";
import { AIConfigService } from "./ai-config.service";


export type FocusArea =
  | "Architecture"
  | "Performance"
  | "Maintainability"
  | "Security"
  | "Code Quality"
  | "General"
  | string;

export type RefactoringPriority = "High" | "Medium" | "Low";
export type RefactoringImpact = "High" | "Medium" | "Low";
export type RefactoringEffort = "Small" | "Medium" | "Large";

export interface RefactoringOpportunity {
  /** Title of the refactoring task */
  title: string;
  /** Detailed description of the opportunity */
  description: string;
  /** Priority level */
  priority: RefactoringPriority;
  /** Estimated impact on code quality/performance */
  estimatedImpact: RefactoringImpact;
  /** Estimated effort required */
  estimatedEffort: RefactoringEffort;
  /** Recommended execution step order (1-indexed) */
  recommendedOrder: number;
  /** Potential risks associated with this refactoring step */
  risks: string[];
  /** Affected source files (if identifiable) */
  affectedFiles?: string[];
}

export interface RefactoringPlanResult {
  /** Executive summary of the refactoring strategy */
  executiveSummary: string;
  /** List of structured refactoring opportunities */
  opportunities: RefactoringOpportunity[];
  /** Overall priority of the plan */
  overallPriority: RefactoringPriority;
  /** Overall estimated impact */
  overallEstimatedImpact: string;
  /** Overall estimated effort */
  overallEstimatedEffort: string;
  /** Sequential step order summary */
  recommendedStepOrder: string[];
  /** Consolidated key risks across all steps */
  keyRisks: string[];
  /** Full raw markdown refactoring plan generated by the LLM */
  markdownPlan: string;
  /** Citable source references */
  sources: SourceReference[];
  /** Planning metadata */
  metadata: {
    repository: string;
    focusArea: string;
    complexity: string;
    intent: string;
    contextDomainsUsed: ContextDomain[];
    strategy: string;
  };
  /** Retrieval and execution statistics */
  stats: KnowledgeRetrievalStats;
}

interface FocusAreaConfig {
  /** Focused retrieval query for RepositoryKnowledgeService */
  retrievalQuery: string;
  /** Custom prompt template builder */
  buildPrompt: (
    workspaceSummary: string,
    knowledgePrompt: string,
    repository: string
  ) => string;
}

/**
 * Extensible Focus Area Configuration Map
 *
 * To add a new refactoring focus area in the future (e.g., "DATABASE_MIGRATION" or "TYPE_SAFETY"):
 *  1. Add a new key to FOCUS_AREA_CONFIGS
 *  2. Provide a targeted retrieval query
 *  3. Define a buildPrompt formatting function
 */
const FOCUS_AREA_CONFIGS: Record<string, FocusAreaConfig> = {
  Architecture: {
    retrievalQuery: "architecture coupling cohesion layer separation controllers services models dependency injection clean architecture",
    buildPrompt: (workspaceSummary, knowledgePrompt, repo) => `
You are a Principal Software Architect crafting a strategic Architectural Refactoring Plan for "${repo}".

${workspaceSummary}

## Objective
Identify architectural debt, layer coupling, circular dependencies, and single-responsibility violations. Design a phased refactoring plan to transition the codebase toward a clean, modular architecture.

---

${knowledgePrompt}
`,
  },

  Performance: {
    retrievalQuery: "performance bottlenecks caching database queries N+1 query async await unoptimized loops memory leaks",
    buildPrompt: (workspaceSummary, knowledgePrompt, repo) => `
You are a Performance Optimization Engineer crafting a Performance Refactoring Plan for "${repo}".

${workspaceSummary}

## Objective
Identify performance bottlenecks, redundant database queries, missing caching layers, blocking sync calls, and memory inefficiencies. Design a prioritized refactoring plan to improve runtime throughput and responsiveness.

---

${knowledgePrompt}
`,
  },

  Maintainability: {
    retrievalQuery: "maintainability technical debt code duplication DRY complexity test coverage refactoring code smells",
    buildPrompt: (workspaceSummary, knowledgePrompt, repo) => `
You are a Lead Software Engineer crafting a Code Maintainability Refactoring Plan for "${repo}".

${workspaceSummary}

## Objective
Identify technical debt, code duplication (DRY violations), overly complex functions, dead code, and low testability areas. Design a refactoring roadmap to simplify code maintenance and onboarding.

---

${knowledgePrompt}
`,
  },

  Security: {
    retrievalQuery: "security vulnerabilities authentication authorization input validation sanitization JWT token secrets exposure CORS",
    buildPrompt: (workspaceSummary, knowledgePrompt, repo) => `
You are a Principal Security Architect crafting a Security Refactoring Plan for "${repo}".

${workspaceSummary}

## Objective
Identify security vulnerabilities, missing input validation, weak authentication flows, exposed secrets, and unhandled security risks. Design a high-priority security hardening roadmap.

---

${knowledgePrompt}
`,
  },

  "Code Quality": {
    retrievalQuery: "code quality naming conventions TypeScript type safety linting error handling standards best practices",
    buildPrompt: (workspaceSummary, knowledgePrompt, repo) => `
You are a Code Quality Lead crafting a Code Quality Refactoring Plan for "${repo}".

${workspaceSummary}

## Objective
Identify code quality issues, loose TypeScript types, inconsistent naming conventions, unhandled errors, and code style deviations. Design a refactoring plan to elevate codebase standards.

---

${knowledgePrompt}
`,
  },

  General: {
    retrievalQuery: "architecture code quality technical debt performance security refactoring opportunities roadmap",
    buildPrompt: (workspaceSummary, knowledgePrompt, repo) => `
You are a Technical Lead crafting a Comprehensive Refactoring Roadmap for "${repo}".

${workspaceSummary}

## Objective
Perform a holistic refactoring analysis balancing architecture, performance, maintainability, security, and code quality. Design a multi-phase refactoring roadmap.

---

${knowledgePrompt}
`,
  },
};

/** Normalize focusArea string to canonical key */
function normalizeFocusArea(focusArea?: string): string {
  if (!focusArea) return "General";
  const norm = focusArea.trim().toLowerCase().replace(/[-_]/g, " ");

  if (norm.includes("arch")) return "Architecture";
  if (norm.includes("perf")) return "Performance";
  if (norm.includes("maintain")) return "Maintainability";
  if (norm.includes("sec")) return "Security";
  if (norm.includes("quality")) return "Code Quality";
  if (norm.includes("general")) return "General";

  return focusArea.trim();
}

/** Extract overall priority from LLM response */
function extractOverallPriority(markdown: string): RefactoringPriority {
  if (/Overall\s*Priority:\s*High/i.test(markdown) || (markdown.match(/Priority:\s*High/gi) || []).length > 1) {
    return "High";
  }
  if (/Overall\s*Priority:\s*Low/i.test(markdown)) {
    return "Low";
  }
  return "Medium";
}

/** Extract key risks list from LLM response */
function extractKeyRisks(markdown: string): string[] {
  const risks: string[] = [];
  const lines = markdown.split("\n");
  let inRisks = false;
  for (const line of lines) {
    if (/^#+\s.*[Rr]isk/.test(line)) {
      inRisks = true;
      continue;
    }
    if (inRisks && /^#+\s/.test(line)) {
      break;
    }
    if (inRisks) {
      const match = line.match(/^\s*[-*]\s+(.+)/) || line.match(/^\s*\d+\.\s+(.+)/);
      if (match) {
        risks.push(match[1].trim());
      }
    }
  }
  return risks.length > 0 ? risks : [
    "Potential regression in un-tested execution paths",
    "Requires thorough integration testing before deployment"
  ];
}

/** Extract recommended step order from LLM response */
function extractStepOrder(markdown: string): string[] {
  const steps: string[] = [];
  const lines = markdown.split("\n");
  let inSteps = false;
  for (const line of lines) {
    if (/^#+\s.*(Recommended Order|Step Order|Phases|Roadmap)/i.test(line)) {
      inSteps = true;
      continue;
    }
    if (inSteps && /^#+\s/.test(line)) {
      break;
    }
    if (inSteps) {
      const match = line.match(/^\s*\d+\.\s+(.+)/) || line.match(/^\s*[-*]\s+(.+)/);
      if (match) {
        steps.push(match[1].trim());
      }
    }
  }
  return steps.length > 0
    ? steps
    : ["Phase 1: High-Priority Hardening", "Phase 2: Architectural Refactoring", "Phase 3: Code Cleanup & Testing"];
}

/**
 * RefactoringPlannerService
 *
 * Responsibility:
 *  1. Accept repository and optional focusArea.
 *  2. Reuse WorkspaceAnalysisService to retrieve baseline repository health & complexity.
 *  3. Perform targeted context retrieval via RepositoryKnowledgeService.
 *  4. Construct a focus-area specific LLM prompt for refactoring planning.
 *  5. Call LLMService and format the response into a structured RefactoringPlanResult model.
 */
export class RefactoringPlannerService extends AIServiceBase {
  private workspaceService: WorkspaceAnalysisService;
  private knowledgeService: RepositoryKnowledgeService;
  private llmService: LLMService;

  constructor(
    workspaceService?: WorkspaceAnalysisService,
    knowledgeService?: RepositoryKnowledgeService,
    llmService?: LLMService,
    configService?: AIConfigService
  ) {
    super("RefactoringPlannerService", configService);
    this.knowledgeService = knowledgeService ?? new RepositoryKnowledgeService(undefined, undefined, undefined, undefined, configService);
    this.workspaceService = workspaceService ?? new WorkspaceAnalysisService(this.knowledgeService, undefined, llmService, configService);
    this.llmService = llmService ?? new LLMService(undefined, configService);
  }

  /**
   * Generates a structured Refactoring Plan for a repository and focus area.
   *
   * @param repository - Repository name / slug
   * @param focusArea  - Optional focus area ("Architecture", "Performance", "Maintainability", "Security", "Code Quality", "General")
   * @param options    - Optional retrieval parameters
   */
  async plan(
    repository: string,
    focusArea?: FocusArea,
    options?: KnowledgeRetrievalOptions
  ): Promise<RefactoringPlanResult> {
    return this.execute(repository, async (context) => {
        const canonicalFocus = normalizeFocusArea(focusArea);

    // 1. Reuse WorkspaceAnalysisService to get baseline repository analysis
    const workspaceAnalysis: WorkspaceAnalysis = await this.workspaceService.analyze(
      repository,
      options
    );

    // 2. Select focus area config
    const config = FOCUS_AREA_CONFIGS[canonicalFocus] ?? FOCUS_AREA_CONFIGS["General"];

    // 3. Perform targeted retrieval via RepositoryKnowledgeService
    const knowledgeResult: RepositoryKnowledgeResult = this.knowledgeService.retrieve(
      repository,
      config.retrievalQuery,
      options
    );

    // 4. Format workspace summary for LLM context
    const workspaceSummary = `
## Repository Overview & Health Summary
- **Repository:** ${workspaceAnalysis.repository}
- **Language:** ${workspaceAnalysis.technologies.language}
- **Framework:** ${workspaceAnalysis.technologies.framework}
- **Database:** ${workspaceAnalysis.technologies.database} (${workspaceAnalysis.technologies.orm})
- **Total Files:** ${workspaceAnalysis.totalFiles}
- **Estimated Complexity:** ${workspaceAnalysis.estimatedComplexity}
- **Major Modules:** ${workspaceAnalysis.majorModules.join(", ") || "None"}
- **Entry Points:** ${workspaceAnalysis.entryPoints.join(", ") || "None"}
- **Initial Recommendations:**
${workspaceAnalysis.aiRecommendations}
`;

    // 5. Build refactoring plan prompt
    const planPrompt = [
      `You are a Senior Software Architect creating a structured, action-oriented Refactoring Plan for "${repository}".`,
      `Focus Area: **${canonicalFocus}**`,
      ``,
      `Your refactoring plan MUST be structured with the following exact Markdown headers:`,
      ``,
      `# Refactoring Plan: ${repository} (${canonicalFocus})`,
      ``,
      `## Executive Summary`,
      `Provide a high-level summary of the refactoring strategy, major debt identified, and expected business/technical outcome.`,
      ``,
      `## Overall Assessment`,
      `- **Overall Priority:** High | Medium | Low`,
      `- **Estimated Impact:** High | Medium | Low`,
      `- **Estimated Effort:** Small | Medium | Large`,
      ``,
      `## Refactoring Opportunities`,
      `List 3 to 6 concrete refactoring tasks. For each task use this format:`,
      `### [Order Number]. [Task Title]`,
      `- **Priority:** High | Medium | Low`,
      `- **Estimated Impact:** High | Medium | Low`,
      `- **Estimated Effort:** Small | Medium | Large`,
      `- **Description:** Explanation of the refactoring task.`,
      `- **Risks:** Potential risks or regressions.`,
      ``,
      `## Recommended Step Order`,
      `Numbered list of phases or steps in order of execution.`,
      ``,
      `## Key Risks & Mitigation`,
      `Bullet list of overall risks and mitigation strategies.`,
      ``,
      `---`,
      ``,
      workspaceSummary,
      ``,
      `---`,
      ``,
      knowledgeResult.prompt,
    ].join("\n");

    // 6. Call LLMService to generate the refactoring plan
    const markdownPlan = await this.trackLLM(context, planPrompt, () =>
      this.llmService.chat(planPrompt)
    );

    // 7. Parse structured metrics from markdown output
    const overallPriority = extractOverallPriority(markdownPlan);
    const keyRisks = extractKeyRisks(markdownPlan);
    const recommendedStepOrder = extractStepOrder(markdownPlan);

    // Extract executive summary (text under "## Executive Summary")
    const execMatch = markdownPlan.match(/##\s+Executive Summary\s*\n+([\s\S]+?)(?=\n##|\n#|$)/);
    const executiveSummary = execMatch
      ? execMatch[1].trim()
      : `Refactoring plan focused on ${canonicalFocus} for ${repository}.`;

    return {
      executiveSummary,
      opportunities: [],      // Full details included in markdownPlan
      overallPriority,
      overallEstimatedImpact: "High",
      overallEstimatedEffort: workspaceAnalysis.estimatedComplexity === "High" || workspaceAnalysis.estimatedComplexity === "Very High" ? "Large" : "Medium",
      recommendedStepOrder,
      keyRisks,
      markdownPlan,
      sources: knowledgeResult.sources,
      metadata: this.buildMetadata(repository, knowledgeResult, { focusArea: canonicalFocus, complexity: workspaceAnalysis.estimatedComplexity }) as any,
      stats: knowledgeResult.stats,
    };
    }, {
      category: "AIResponses",
      payload: { focusArea, options },
    });
  }
}
